### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by CPC-Coder** [FreddyChen/Shine-Kotlin#1]
1. 目前没看到 上传 下载 功能
2. 特定请求 可以加入 菊花
3. 请求方式最好 跟retrofit 方式相同 ,  因为多人开发项目 要求接口统一

**Comment by FreddyChen** [comment]
> 1. 目前没看到 上传 下载 功能
> 2. 特定请求 可以加入 菊花
> 3. 请求方式最好 跟retrofit 方式相同 ,  因为多人开发项目 要求接口统一

回复一下。
1. 后续看使用的人数，如果大家有这个需求的话，可以加上；
2. Loading的话，应该需要调用方实现，因为每个项目对Loading的样式要求可能不一样；
3. 接口统一指的是？麻烦回复一下，谢谢。

**Comment by CPC-Coder** [comment]
2 可以提供相应的接口  请求之前 请求完成 等位置的接口  , 然后demo可以写个菊花案例
3 
![image](https://user-images.githubusercontent.com/26327598/155074311-ad002931-7351-4b77-a607-8a942efe7faa.png)
这种方式传参的,因为不同框架 不同写法,导致一些公司多人的项目 比较混乱,目前retrofit的人数比较多 ,希望沿用该方式

**Comment by FreddyChen** [comment]
> 

2. 感谢反馈，这个后续有时间会加上；
3. 如果用这种方式的话，那还是回到Retrofit ApiService的方式了，那样会导致不通用。Shine后续考虑把Retrofit彻底移除掉，只保留OkHttp
